# 한국주식시장 상장 회사 모두 갖고 오기

## 1. 한국증권거래소에서 모든 종목 코드 갖고 오기

In [2]:
import pandas as pd

# kospi(유가증권)
#kospi_df = pd.read_html('http://kind.krx.co.kr/corpgeneral/corpList.do?method=download&searchType=13&marketType=stockMkt', index_col=["종목코드"], header=0)[0]
kospi_df = pd.read_html('http://kind.krx.co.kr/corpgeneral/corpList.do?method=download&searchType=13&marketType=stockMkt', header=0)[0]

# kosdaq
kosdaq_df = pd.read_html('http://kind.krx.co.kr/corpgeneral/corpList.do?method=download&searchType=13&marketType=kosdaqMkt', header=0)[0]

In [3]:
print("kospi = ", kospi_df.shape)
kospi_df.head(5)

kospi =  (777, 9)

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,BYC,1460,봉제의복 제조업,"메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급",1975-06-02,12월,유 중 화,http://www.byc.co.kr,서울특별시
1,CJ CGV,79160,"영화, 비디오물, 방송프로그램 제작 및 배급업","영화상영,영화관 운영",2004-12-24,12월,서 정,http://www.cgv.co.kr,서울특별시
2,DB손해보험,5830,보험업,"자동차보험,화재보험,해상보험,특종보험,장기보험",1973-06-28,12월,김정남,http://www.idbins.com,서울특별시
3,DSR제강,69730,1차 철강 제조업,"와이어로프,각종 경강선,철선제품,PC강선,아연도 강연선 제조",2003-01-28,12월,홍하종,http://www.dsrcorp.com,전라남도
4,KB금융,105560,기타 금융업,-,2008-10-10,12월,윤종규,http://www.kbfg.com,서울특별시

In [4]:
print("kosdaq = ", kosdaq_df.shape)
kosdaq_df.head(5)

kosdaq =  (1269, 9)

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역
0,CJ오쇼핑,35760,텔레비전 방송업,"의류, 생활주방, 가전제품, 보석, 기타",1999-11-23,12월,허민회,http://www.cjmall.com,서울특별시
1,CMG제약,58820,의약품 제조업,의약품,2001-08-31,12월,이주형,http://www.skynewpharm.com,서울특별시
2,IBKS제8호스팩,277410,금융 지원 서비스업,기업인수합병,2017-09-29,12월,박광열,NaN,서울특별시
3,KG이니시스,35600,소프트웨어 개발 및 공급업,전자지불서비스,2002-11-22,12월,곽재선,http://www.inicis.com,경기도
4,SDN,99220,기계장비 및 관련 물품 도매업,"태양광기자재 및 선박용엔진 도매, 태양광발전시스템 구축 및 설계",2009-05-19,12월,최기혁,http://www.sdn-i.com,경기도

### 시장구분(KOSPI, KOSDAQ) 컬럼 추가하기

In [5]:
kospi_df['marketType'] = 'kospi'

kospi_df.head(5)

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역,marketType
0,BYC,1460,봉제의복 제조업,"메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급",1975-06-02,12월,유 중 화,http://www.byc.co.kr,서울특별시,kospi
1,CJ CGV,79160,"영화, 비디오물, 방송프로그램 제작 및 배급업","영화상영,영화관 운영",2004-12-24,12월,서 정,http://www.cgv.co.kr,서울특별시,kospi
2,DB손해보험,5830,보험업,"자동차보험,화재보험,해상보험,특종보험,장기보험",1973-06-28,12월,김정남,http://www.idbins.com,서울특별시,kospi
3,DSR제강,69730,1차 철강 제조업,"와이어로프,각종 경강선,철선제품,PC강선,아연도 강연선 제조",2003-01-28,12월,홍하종,http://www.dsrcorp.com,전라남도,kospi
4,KB금융,105560,기타 금융업,-,2008-10-10,12월,윤종규,http://www.kbfg.com,서울특별시,kospi

In [6]:
kosdaq_df['marketType'] = 'kosdaq'

kosdaq_df.head(5)

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역,marketType
0,CJ오쇼핑,35760,텔레비전 방송업,"의류, 생활주방, 가전제품, 보석, 기타",1999-11-23,12월,허민회,http://www.cjmall.com,서울특별시,kosdaq
1,CMG제약,58820,의약품 제조업,의약품,2001-08-31,12월,이주형,http://www.skynewpharm.com,서울특별시,kosdaq
2,IBKS제8호스팩,277410,금융 지원 서비스업,기업인수합병,2017-09-29,12월,박광열,NaN,서울특별시,kosdaq
3,KG이니시스,35600,소프트웨어 개발 및 공급업,전자지불서비스,2002-11-22,12월,곽재선,http://www.inicis.com,경기도,kosdaq
4,SDN,99220,기계장비 및 관련 물품 도매업,"태양광기자재 및 선박용엔진 도매, 태양광발전시스템 구축 및 설계",2009-05-19,12월,최기혁,http://www.sdn-i.com,경기도,kosdaq

### kospi, kosdaq을 1개의 dataframe으로 합치기

In [7]:
frames = [kospi_df, kosdaq_df]
stock_df = pd.concat(frames)

print(stock_df.shape)
stock_df.head(5)

(2046, 10)

,회사명,종목코드,업종,주요제품,상장일,결산월,대표자명,홈페이지,지역,marketType
0,BYC,1460,봉제의복 제조업,"메리야스,란제리 제조,도매/건축공사/부동산 임대,분양,공급",1975-06-02,12월,유 중 화,http://www.byc.co.kr,서울특별시,kospi
1,CJ CGV,79160,"영화, 비디오물, 방송프로그램 제작 및 배급업","영화상영,영화관 운영",2004-12-24,12월,서 정,http://www.cgv.co.kr,서울특별시,kospi
2,DB손해보험,5830,보험업,"자동차보험,화재보험,해상보험,특종보험,장기보험",1973-06-28,12월,김정남,http://www.idbins.com,서울특별시,kospi
3,DSR제강,69730,1차 철강 제조업,"와이어로프,각종 경강선,철선제품,PC강선,아연도 강연선 제조",2003-01-28,12월,홍하종,http://www.dsrcorp.com,전라남도,kospi
4,KB금융,105560,기타 금융업,-,2008-10-10,12월,윤종규,http://www.kbfg.com,서울특별시,kospi

### 필요한 항목만 갖고 오기

In [8]:
feature_names = ['회사명', '종목코드', '업종', '결산월', 'marketType']
stock_train = stock_df[feature_names]

print(stock_train.shape)
stock_train.head(5)

(2046, 5)

      회사명    종목코드                         업종  결산월 marketType
0     BYC    1460                   봉제의복 제조업  12월      kospi
1  CJ CGV   79160  영화, 비디오물, 방송프로그램 제작 및 배급업  12월      kospi
2  DB손해보험    5830                        보험업  12월      kospi
3   DSR제강   69730                  1차 철강 제조업  12월      kospi
4    KB금융  105560                     기타 금융업  12월      kospi

In [9]:
# stock_train[stock_train['회사명'] == '삼성전자']

stock_train.index

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268],
           dtype='int64', length=2046)

## 2. 각 종목들의 일일 주가 정보 갖고 오기

## Naver에서 일별 주가 정보 갖고 오기

In [10]:
stock_train.query("회사명=='{}'".format('삼성전자'))['종목코드'].to_string(index=False)

'5930'

In [11]:
# 종목 이름을 입력하면 종목에 해당하는 코드를 불러와 # 네이버 금융(http://finance.naver.com)에 넣어줌 
def get_url(item_name, code_df): 
    code = stock_train.query("회사명=='{}'".format(item_name))['종목코드'].to_string(index=False)
    url = 'http://finance.naver.com/item/sise_day.nhn?code={code}'.format(code=code)
    print("요청 URL = {}".format(url))
    return url

In [12]:
# 신라젠의 일자데이터 url 가져오기 
item_name='BYC' 
url = get_url(item_name, stock_train)

# 일자 데이터를 담을 df라는 DataFrame 정의
df = pd.DataFrame()

# 1페이지에서 20페이지의 데이터만 가져오기
for page in range(1, 21): 
    pg_url = '{url}&page={page}'.format(url=url, page=page)
    df = df.append(pd.read_html(pg_url, header=0)[0], ignore_index=True) 

# df.dropna()를 이용해 결측값 있는 행 제거 
df = df.dropna() 

# 상위 5개 데이터 확인하기
df.head()

요청 URL = http://finance.naver.com/item/sise_day.nhn?code=1460

Empty DataFrame
Columns: [날짜, 종가, 전일비, 시가, 고가, 저가, 거래량]
Index: []

## 재무제표 갖고 오기

In [60]:
def get_finacial_statements_url(code, ifrs_type=4, unit='Y'):
    url_tmpl = 'http://companyinfo.stock.naver.com/v1/company/ajax/cF1001.aspx?cmp_cd=%s&fin_typ=%s&freq_typ=%s'
    url = url_tmpl % (code, ifrs_type, unit) # 삼성전자, 4(IFRS 연결), Y:년 단위
    print(url)
    dfs = pd.read_html(url, encoding='utf8')    
    # dfs
    df = dfs[0]
    # print(df)
    df = df.set_index('주요재무정보')
    return df

In [61]:
# 리스트로 전환
def get_financial_statements_infos(df):
    cols = []
    for year in range(2012, 2020):
        cols.append(str(year) + '/12')    
    df.columns = cols

    indexes = []
    for i in range(0, df.index.size):
        indexes.append(df.index[i][0])
        
    new_index_dict = dict(zip(df.index, indexes))
    df.rename(new_index_dict, axis='index', inplace=True)  
    
    df.fillna(0, inplace=True)
    
    dft = df.T

    # 첫번째 컬럼 이름을 data로 변경
    dft.rename(columns={'주요재무정보':'date'}, inplace=True)

    # 인덱스를 날짜형식(datetime)으로 변환
    dft.index = pd.to_datetime(dft.index)
    
    return dft

In [43]:
# 증자 여부: 증자기업 나쁜 기업. 즉, '증자여부'가 0이어야지 됨.
def check_increase_capital(df):
#     df['자본금'] = df['자본금'].astype(float).fillna(0.0)
    df['증자여부'] = 0.0
    for index in range(1, len(df.index)):
        df.loc[index:index+1,'증자여부'] = df.iloc[index-1]['자본금'] - df.iloc[index]['자본금']

In [64]:
df = get_finacial_statements_url('079160')

http://companyinfo.stock.naver.com/v1/company/ajax/cF1001.aspx?cmp_cd=079160&fin_typ=4&freq_typ=Y

In [65]:
df = get_financial_statements_infos(df)
df

주요재무정보,매출액,영업이익,영업이익(발표기준),세전계속사업이익,당기순이익,당기순이익(지배),당기순이익(비지배),자산총계,부채총계,자본총계,...,부채비율,자본유보율,EPS(원),PER(배),BPS(원),PBR(배),현금DPS(원),현금배당수익률,현금배당성향(%),발행주식수(보통주)
2012-12-01,9159.0,515.0,515.0,151.0,121.0,127.0,-6.0,10992.0,7205.0,3786.0,...,190.30,3480.72,607.0,71.66,17591.0,2.47,350.0,0.80,58.40,21161313.0
2013-12-01,10393.0,521.0,521.0,346.0,160.0,167.0,-6.0,12549.0,8637.0,3912.0,...,220.80,3539.92,787.0,68.60,18048.0,2.99,350.0,0.65,44.46,21161313.0
2014-12-01,11935.0,669.0,669.0,728.0,522.0,519.0,3.0,14176.0,9724.0,4452.0,...,218.43,3948.38,2455.0,51.33,19899.0,6.33,350.0,0.28,14.26,21161313.0
2015-12-01,14322.0,703.0,703.0,180.0,56.0,123.0,-67.0,25418.0,16213.0,9205.0,...,176.13,3967.39,583.0,120.74,17654.0,3.99,350.0,0.50,60.03,21161313.0
2016-12-01,17144.0,862.0,862.0,115.0,100.0,-14.0,114.0,24601.0,16824.0,7777.0,...,216.35,3873.67,-66.0,-1119.52,14554.0,5.10,350.0,0.47,-528.08,21161313.0
2017-12-01,18965.0,1088.0,0.0,744.0,558.0,526.0,0.0,26379.0,17234.0,9142.0,...,188.52,0.00,2486.0,26.02,17283.0,3.74,356.0,0.55,0.14,0.0
2018-12-01,21061.0,1326.0,0.0,1032.0,788.0,743.0,0.0,27693.0,17896.0,9819.0,...,182.27,0.00,3512.0,18.42,19887.0,3.25,370.0,0.57,0.11,0.0
2019-12-01,21480.0,1240.0,0.0,0.0,840.0,890.0,0.0,28820.0,0.0,10980.0,...,0.00,0.00,4206.0,15.38,19989.0,3.24,0.0,0.00,0.00,0.0

In [66]:
df.iloc[0]['자본금'] - df.iloc[1]['자본금']

0.0

In [47]:
df = check_increase_capital(df)

In [67]:
df.head()

주요재무정보,매출액,영업이익,영업이익(발표기준),세전계속사업이익,당기순이익,당기순이익(지배),당기순이익(비지배),자산총계,부채총계,자본총계,...,부채비율,자본유보율,EPS(원),PER(배),BPS(원),PBR(배),현금DPS(원),현금배당수익률,현금배당성향(%),발행주식수(보통주)
2012-12-01,9159.0,515.0,515.0,151.0,121.0,127.0,-6.0,10992.0,7205.0,3786.0,...,190.30,3480.72,607.0,71.66,17591.0,2.47,350.0,0.80,58.40,21161313.0
2013-12-01,10393.0,521.0,521.0,346.0,160.0,167.0,-6.0,12549.0,8637.0,3912.0,...,220.80,3539.92,787.0,68.60,18048.0,2.99,350.0,0.65,44.46,21161313.0
2014-12-01,11935.0,669.0,669.0,728.0,522.0,519.0,3.0,14176.0,9724.0,4452.0,...,218.43,3948.38,2455.0,51.33,19899.0,6.33,350.0,0.28,14.26,21161313.0
2015-12-01,14322.0,703.0,703.0,180.0,56.0,123.0,-67.0,25418.0,16213.0,9205.0,...,176.13,3967.39,583.0,120.74,17654.0,3.99,350.0,0.50,60.03,21161313.0
2016-12-01,17144.0,862.0,862.0,115.0,100.0,-14.0,114.0,24601.0,16824.0,7777.0,...,216.35,3873.67,-66.0,-1119.52,14554.0,5.10,350.0,0.47,-528.08,21161313.0

주요재무정보
매출액               9159.00
영업이익               515.00
영업이익(발표기준)         515.00
세전계속사업이익           151.00
당기순이익              121.00
당기순이익(지배)          127.00
당기순이익(비지배)          -6.00
자산총계             10992.00
부채총계              7205.00
자본총계              3786.00
자본총계(지배)          3722.00
자본총계(비지배)           64.00
자본금                106.00
영업활동현금흐름           615.00
투자활동현금흐름         -2076.00
재무활동현금흐름           490.00
CAPEX             1596.00
FCF               -981.00
이자발생부채            3919.00
영업이익률                5.62
순이익률                 1.32
ROE(%)               3.53
ROA(%)               1.15
부채비율               190.30
자본유보율             3480.72
EPS(원)             607.00
PER(배)              71.66
BPS(원)           17591.00
PBR(배)               2.47
현금DPS(원)           350.00
현금배당수익률              0.80
현금배당성향(%)           58.40
발행주식수(보통주)    21161313.00
Name: 2013-12-01 00:00:00, dtype: float64