In [17]:
import pandas as pd

In [18]:
url_tmpl = 'http://companyinfo.stock.naver.com/v1/company/ajax/cF1001.aspx?cmp_cd=%s&fin_typ=%s&freq_typ=%s'
url = url_tmpl % ('005930', '4', 'Y') # 삼성전자, 4(IFRS 연결), Y:년 단위

dfs = pd.read_html(url, encoding='utf8')
# dfs
df = dfs[0]
# print(df)
df = df.set_index('주요재무정보')
df.head(10) # 10개 항목만 표시(실제 32개 항목)

,연간,Unnamed: 2_level_0,Unnamed: 3_level_0,Unnamed: 4_level_0,Unnamed: 5_level_0,Unnamed: 6_level_0,Unnamed: 7_level_0,Unnamed: 8_level_0
,\n\t\t\t\t\t\t\t\t\t2014/12\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t(IFRS연결)\n\t\t\t\t\t\t\t\t,\n\t\t\t\t\t\t\t\t\t2015/12\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t(IFRS연결)\n\t\t\t\t\t\t\t\t,\n\t\t\t\t\t\t\t\t\t2016/12\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t(IFRS연결)\n\t\t\t\t\t\t\t\t,\n\t\t\t\t\t\t\t\t\t2017/12\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t(IFRS연결)\n\t\t\t\t\t\t\t\t,\n\t\t\t\t\t\t\t\t\t2018/12(E)\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t(IFRS연결)\n\t\t\t\t\t\t\t\t,\n\t\t\t\t\t\t\t\t\t2019/12(E)\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t(IFRS연결)\n\t\t\t\t\t\t\t\t,\n\t\t\t\t\t\t\t\t\t2020/12(E)\n\t\t\t\t\t\t\t\t\t\n\t\t\t\t\t\t\t\t\t(IFRS연결)\n\t\t\t\t\t\t\t\t,Unnamed: 8_level_1
주요재무정보,,,,,,,,
"(매출액,)",2286927.0,2062060.0,2006535.0,2018667.0,2395754.0,2609853.0,2707078.0,2789011.0
"(영업이익,)",367850.0,250251.0,264134.0,292407.0,536450.0,630163.0,636614.0,653598.0
"(영업이익(발표기준),)",367850.0,250251.0,264134.0,292407.0,536450.0,NaN,NaN,NaN
"(세전계속사업이익,)",383643.0,278750.0,259610.0,307137.0,561960.0,651990.0,661092.0,683498.0
"(당기순이익,)",304748.0,233944.0,190601.0,227261.0,421867.0,486860.0,493402.0,517531.0
"(당기순이익(지배),)",298212.0,230825.0,186946.0,224157.0,413446.0,478098.0,484541.0,509688.0
"(당기순이익(비지배),)",6535.0,3119.0,3655.0,3104.0,8422.0,NaN,NaN,NaN
"(자산총계,)",2140750.0,2304230.0,2421795.0,2621743.0,3017521.0,3467857.0,3891569.0,4036498.0
"(부채총계,)",640590.0,623348.0,631197.0,692113.0,872607.0,861430.0,897671.0,928223.0
"(자본총계,)",1500160.0,1680882.0,1790598.0,1929630.0,2144914.0,2603368.0,2984159.0,3354682.0

# 컬럼 변환

In [19]:
# 리스트로 전환
cols = []

for year in range(2012, 2020):
    cols.append(str(year) + '/12')
    
cols

['2012/12',
 '2013/12',
 '2014/12',
 '2015/12',
 '2016/12',
 '2017/12',
 '2018/12',
 '2019/12']

In [20]:
df.columns = cols
df.head()

,2012/12,2013/12,2014/12,2015/12,2016/12,2017/12,2018/12,2019/12
주요재무정보,,,,,,,,
"(매출액,)",2286927.0,2062060.0,2006535.0,2018667.0,2395754.0,2609853.0,2707078.0,2789011.0
"(영업이익,)",367850.0,250251.0,264134.0,292407.0,536450.0,630163.0,636614.0,653598.0
"(영업이익(발표기준),)",367850.0,250251.0,264134.0,292407.0,536450.0,NaN,NaN,NaN
"(세전계속사업이익,)",383643.0,278750.0,259610.0,307137.0,561960.0,651990.0,661092.0,683498.0
"(당기순이익,)",304748.0,233944.0,190601.0,227261.0,421867.0,486860.0,493402.0,517531.0

# Index  변환

In [21]:
indexes = []

for i in range(0, df.index.size):
    indexes.append(df.index[i][0])
    
indexes

['매출액',
 '영업이익',
 '영업이익(발표기준)',
 '세전계속사업이익',
 '당기순이익',
 '당기순이익(지배)',
 '당기순이익(비지배)',
 '자산총계',
 '부채총계',
 '자본총계',
 '자본총계(지배)',
 '자본총계(비지배)',
 '자본금',
 '영업활동현금흐름',
 '투자활동현금흐름',
 '재무활동현금흐름',
 'CAPEX',
 'FCF',
 '이자발생부채',
 '영업이익률',
 '순이익률',
 'ROE(%)',
 'ROA(%)',
 '부채비율',
 '자본유보율',
 'EPS(원)',
 'PER(배)',
 'BPS(원)',
 'PBR(배)',
 '현금DPS(원)',
 '현금배당수익률',
 '현금배당성향(%)',
 '발행주식수(보통주)']

In [22]:
df.head(5)

,2012/12,2013/12,2014/12,2015/12,2016/12,2017/12,2018/12,2019/12
주요재무정보,,,,,,,,
"(매출액,)",2286927.0,2062060.0,2006535.0,2018667.0,2395754.0,2609853.0,2707078.0,2789011.0
"(영업이익,)",367850.0,250251.0,264134.0,292407.0,536450.0,630163.0,636614.0,653598.0
"(영업이익(발표기준),)",367850.0,250251.0,264134.0,292407.0,536450.0,NaN,NaN,NaN
"(세전계속사업이익,)",383643.0,278750.0,259610.0,307137.0,561960.0,651990.0,661092.0,683498.0
"(당기순이익,)",304748.0,233944.0,190601.0,227261.0,421867.0,486860.0,493402.0,517531.0

In [23]:
# new_indexes = {v: k for v, k in enumerate(indexes)}

new_index_dict = dict(zip(df.index, indexes))
print(new_index_dict)

df.rename(new_index_dict, axis='index', inplace=True)
df.head(5)

{('매출액',): '매출액', ('영업이익',): '영업이익', ('영업이익(발표기준)',): '영업이익(발표기준)', ('세전계속사업이익',): '세전계속사업이익', ('당기순이익',): '당기순이익', ('당기순이익(지배)',): '당기순이익(지배)', ('당기순이익(비지배)',): '당기순이익(비지배)', ('자산총계',): '자산총계', ('부채총계',): '부채총계', ('자본총계',): '자본총계', ('자본총계(지배)',): '자본총계(지배)', ('자본총계(비지배)',): '자본총계(비지배)', ('자본금',): '자본금', ('영업활동현금흐름',): '영업활동현금흐름', ('투자활동현금흐름',): '투자활동현금흐름', ('재무활동현금흐름',): '재무활동현금흐름', ('CAPEX',): 'CAPEX', ('FCF',): 'FCF', ('이자발생부채',): '이자발생부채', ('영업이익률',): '영업이익률', ('순이익률',): '순이익률', ('ROE(%)',): 'ROE(%)', ('ROA(%)',): 'ROA(%)', ('부채비율',): '부채비율', ('자본유보율',): '자본유보율', ('EPS(원)',): 'EPS(원)', ('PER(배)',): 'PER(배)', ('BPS(원)',): 'BPS(원)', ('PBR(배)',): 'PBR(배)', ('현금DPS(원)',): '현금DPS(원)', ('현금배당수익률',): '현금배당수익률', ('현금배당성향(%)',): '현금배당성향(%)', ('발행주식수(보통주)',): '발행주식수(보통주)'}

,2012/12,2013/12,2014/12,2015/12,2016/12,2017/12,2018/12,2019/12
주요재무정보,,,,,,,,
매출액,2286927.0,2062060.0,2006535.0,2018667.0,2395754.0,2609853.0,2707078.0,2789011.0
영업이익,367850.0,250251.0,264134.0,292407.0,536450.0,630163.0,636614.0,653598.0
영업이익(발표기준),367850.0,250251.0,264134.0,292407.0,536450.0,NaN,NaN,NaN
세전계속사업이익,383643.0,278750.0,259610.0,307137.0,561960.0,651990.0,661092.0,683498.0
당기순이익,304748.0,233944.0,190601.0,227261.0,421867.0,486860.0,493402.0,517531.0

# NaN을 0.0 숫자로 바꾸기

In [24]:
df.fillna(0, inplace=True)
df.head()

,2012/12,2013/12,2014/12,2015/12,2016/12,2017/12,2018/12,2019/12
주요재무정보,,,,,,,,
매출액,2286927.0,2062060.0,2006535.0,2018667.0,2395754.0,2609853.0,2707078.0,2789011.0
영업이익,367850.0,250251.0,264134.0,292407.0,536450.0,630163.0,636614.0,653598.0
영업이익(발표기준),367850.0,250251.0,264134.0,292407.0,536450.0,0.0,0.0,0.0
세전계속사업이익,383643.0,278750.0,259610.0,307137.0,561960.0,651990.0,661092.0,683498.0
당기순이익,304748.0,233944.0,190601.0,227261.0,421867.0,486860.0,493402.0,517531.0

# column & row change

In [25]:
dft = df.T

# 첫번째 컬럼 이름을 data로 변경
dft.rename(columns={'주요재무정보':'date'}, inplace=True)

# 인덱스를 날짜형식(datetime)으로 변환
dft.index = pd.to_datetime(dft.index)

dft[['매출액', '당기순이익', '부채총계', 'PER(배)' , 'PBR(배)', '현금배당수익률', '자본금']]

주요재무정보            매출액     당기순이익      부채총계  PER(배)  PBR(배)  현금배당수익률     자본금
2012-12-01  2286927.0  304748.0  640590.0    7.83    1.43     1.04  8975.0
2013-12-01  2062060.0  233944.0  623348.0    9.78    1.23     1.51  8975.0
2014-12-01  2006535.0  190601.0  631197.0   11.47    1.06     1.67  8975.0
2015-12-01  2018667.0  227261.0  692113.0   13.18    1.35     1.58  8975.0
2016-12-01  2395754.0  421867.0  872607.0    9.40    1.67     1.67  8975.0
2017-12-01  2609853.0  486860.0  861430.0    7.62    1.34     2.78  8896.0
2018-12-01  2707078.0  493402.0  897671.0    7.51    1.17     2.83  8896.0
2019-12-01  2789011.0  517531.0  928223.0    7.14    1.04     3.24  8846.0

In [26]:
# 증자 여부: 증자기업 나쁜 기업. 즉, '증자여부'가 0이어야지 됨.
def check_increase_capital(df):
    df['증자여부'] = 0.0
    for index in range(1, len(dft.index)):
        df.loc[index:index+1,'증자여부'] = df.iloc[index-1]['자본금'] - dft.iloc[index]['자본금']

In [27]:
check_increase_capital(dft)

In [28]:
dft[['매출액', '당기순이익', '부채총계', 'PER(배)' , 'PBR(배)', '현금배당수익률', '자본금', '증자여부']]

주요재무정보,매출액,당기순이익,부채총계,PER(배),PBR(배),현금배당수익률,자본금,증자여부
2012-12-01,2286927.0,304748.0,640590.0,7.83,1.43,1.04,8975.0,0.0
2013-12-01,2062060.0,233944.0,623348.0,9.78,1.23,1.51,8975.0,0.0
2014-12-01,2006535.0,190601.0,631197.0,11.47,1.06,1.67,8975.0,0.0
2015-12-01,2018667.0,227261.0,692113.0,13.18,1.35,1.58,8975.0,0.0
2016-12-01,2395754.0,421867.0,872607.0,9.40,1.67,1.67,8975.0,0.0
2017-12-01,2609853.0,486860.0,861430.0,7.62,1.34,2.78,8896.0,79.0
2018-12-01,2707078.0,493402.0,897671.0,7.51,1.17,2.83,8896.0,0.0
2019-12-01,2789011.0,517531.0,928223.0,7.14,1.04,3.24,8846.0,50.0

In [29]:
df.index.name

'주요재무정보'

In [30]:
dft.loc[0:1,'증자여부'] = 12.0

In [31]:
dft

주요재무정보,매출액,영업이익,영업이익(발표기준),세전계속사업이익,당기순이익,당기순이익(지배),당기순이익(비지배),자산총계,부채총계,자본총계,...,자본유보율,EPS(원),PER(배),BPS(원),PBR(배),현금DPS(원),현금배당수익률,현금배당성향(%),발행주식수(보통주),증자여부
2012-12-01,2286927.0,367850.0,367850.0,383643.0,304748.0,298212.0,6535.0,2140750.0,640590.0,1500160.0,...,17047.55,175282.0,7.83,958040.0,1.43,14300.0,1.04,7.23,147299337.0,12.0
2013-12-01,2062060.0,250251.0,250251.0,278750.0,233944.0,230825.0,3119.0,2304230.0,623348.0,1680882.0,...,19379.47,135673.0,9.78,1083205.0,1.23,20000.0,1.51,13.00,147299337.0,0.0
2014-12-01,2006535.0,264134.0,264134.0,259610.0,190601.0,186946.0,3655.0,2421795.0,631197.0,1790598.0,...,21117.88,109883.0,11.47,1185738.0,1.06,21000.0,1.67,16.42,147299337.0,0.0
2015-12-01,2018667.0,292407.0,292407.0,307137.0,227261.0,224157.0,3104.0,2621743.0,692113.0,1929630.0,...,22004.14,136760.0,13.18,1331779.0,1.35,28500.0,1.58,17.81,140679337.0,0.0
2016-12-01,2395754.0,536450.0,536450.0,561960.0,421867.0,413446.0,8422.0,3017521.0,872607.0,2144914.0,...,24536.12,271061.0,9.40,1521349.0,1.67,42500.0,1.67,14.09,129098494.0,0.0
2017-12-01,2609853.0,630163.0,0.0,651990.0,486860.0,478098.0,0.0,3467857.0,861430.0,2603368.0,...,0.00,326280.0,7.62,1856415.0,1.34,69147.0,2.78,0.19,0.0,79.0
2018-12-01,2707078.0,636614.0,0.0,661092.0,493402.0,484541.0,0.0,3891569.0,897671.0,2984159.0,...,0.00,330837.0,7.51,2127874.0,1.17,70458.0,2.83,0.19,0.0,0.0
2019-12-01,2789011.0,653598.0,0.0,683498.0,517531.0,509688.0,0.0,4036498.0,928223.0,3354682.0,...,0.00,348007.0,7.14,2380998.0,1.04,80525.0,3.24,0.20,0.0,50.0

## excel 저장

In [53]:
dft.iloc[4:6]['매출액']

2016-12-01    2395754.0
2017-12-01    2609853.0
Name: 매출액, dtype: float64

In [54]:
# Create a Pandas Excel writer using XlsxWriter as the engine.
writer = pd.ExcelWriter('pandas_multiple.xlsx', engine='xlsxwriter')

In [56]:
dft.iloc[4:6]['매출액'].to_excel(writer, index=True, sheet_name='매출액')
writer.save()